//This file is automatically generated.
//Do not attempt to make changes to this file because the changes will be erased and overwritten.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;

namespace OpenDentBusiness.Crud{
	internal class PerioMeasureCrud {
		///<summary>Gets one PerioMeasure object from the database using the primary key.  Returns null if not found.</summary>
		internal static PerioMeasure SelectOne(long perioMeasureNum){
			string command="SELECT * FROM periomeasure "
				+"WHERE PerioMeasureNum = "+POut.Long(perioMeasureNum)+" LIMIT 1";
			List<PerioMeasure> list=TableToList(Db.GetTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets one PerioMeasure object from the database using a query.</summary>
		internal static PerioMeasure SelectOne(string command){
			if(RemotingClient.RemotingRole==RemotingRole.ClientWeb) {
				throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n"+command);
			}
			List<PerioMeasure> list=TableToList(Db.GetTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets a list of PerioMeasure objects from the database using a query.</summary>
		internal static List<PerioMeasure> SelectMany(string command){
			if(RemotingClient.RemotingRole==RemotingRole.ClientWeb) {
				throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n"+command);
			}
			List<PerioMeasure> list=TableToList(Db.GetTable(command));
			return list;
		}

		///<summary>Converts a DataTable to a list of objects.</summary>
		internal static List<PerioMeasure> TableToList(DataTable table){
			List<PerioMeasure> retVal=new List<PerioMeasure>();
			PerioMeasure perioMeasure;
			for(int i=0;i<table.Rows.Count;i++) {
				perioMeasure=new PerioMeasure();
				perioMeasure.PerioMeasureNum= PIn.Long  (table.Rows[i]["PerioMeasureNum"].ToString());
				perioMeasure.PerioExamNum   = PIn.Long  (table.Rows[i]["PerioExamNum"].ToString());
				perioMeasure.SequenceType   = (PerioSequenceType)PIn.Int(table.Rows[i]["SequenceType"].ToString());
				perioMeasure.IntTooth       = PIn.Int   (table.Rows[i]["IntTooth"].ToString());
				perioMeasure.ToothValue     = PIn.Int   (table.Rows[i]["ToothValue"].ToString());
				perioMeasure.MBvalue        = PIn.Int   (table.Rows[i]["MBvalue"].ToString());
				perioMeasure.Bvalue         = PIn.Int   (table.Rows[i]["Bvalue"].ToString());
				perioMeasure.DBvalue        = PIn.Int   (table.Rows[i]["DBvalue"].ToString());
				perioMeasure.MLvalue        = PIn.Int   (table.Rows[i]["MLvalue"].ToString());
				perioMeasure.Lvalue         = PIn.Int   (table.Rows[i]["Lvalue"].ToString());
				perioMeasure.DLvalue        = PIn.Int   (table.Rows[i]["DLvalue"].ToString());
				retVal.Add(perioMeasure);
			}
			return retVal;
		}

		///<summary>Inserts one PerioMeasure into the database.  Returns the new priKey.</summary>
		internal static long Insert(PerioMeasure perioMeasure){
			return Insert(perioMeasure,false);
		}

		///<summary>Inserts one PerioMeasure into the database.  Provides option to use the existing priKey.</summary>
		internal static long Insert(PerioMeasure perioMeasure,bool useExistingPK){
			if(!useExistingPK && PrefC.RandomKeys) {
				perioMeasure.PerioMeasureNum=ReplicationServers.GetKey("periomeasure","PerioMeasureNum");
			}
			string command="INSERT INTO periomeasure (";
			if(useExistingPK || PrefC.RandomKeys) {
				command+="PerioMeasureNum,";
			}
			command+="PerioExamNum,SequenceType,IntTooth,ToothValue,MBvalue,Bvalue,DBvalue,MLvalue,Lvalue,DLvalue) VALUES(";
			if(useExistingPK || PrefC.RandomKeys) {
				command+=POut.Long(perioMeasure.PerioMeasureNum)+",";
			}
			command+=
				     POut.Long  (perioMeasure.PerioExamNum)+","
				+    POut.Int   ((int)perioMeasure.SequenceType)+","
				+    POut.Int   (perioMeasure.IntTooth)+","
				+    POut.Int   (perioMeasure.ToothValue)+","
				+    POut.Int   (perioMeasure.MBvalue)+","
				+    POut.Int   (perioMeasure.Bvalue)+","
				+    POut.Int   (perioMeasure.DBvalue)+","
				+    POut.Int   (perioMeasure.MLvalue)+","
				+    POut.Int   (perioMeasure.Lvalue)+","
				+    POut.Int   (perioMeasure.DLvalue)+")";
			if(useExistingPK || PrefC.RandomKeys) {
				Db.NonQ(command);
			}
			else {
				perioMeasure.PerioMeasureNum=Db.NonQ(command,true);
			}
			return perioMeasure.PerioMeasureNum;
		}

		///<summary>Updates one PerioMeasure in the database.</summary>
		internal static void Update(PerioMeasure perioMeasure){
			string command="UPDATE periomeasure SET "
				+"PerioExamNum   =  "+POut.Long  (perioMeasure.PerioExamNum)+", "
				+"SequenceType   =  "+POut.Int   ((int)perioMeasure.SequenceType)+", "
				+"IntTooth       =  "+POut.Int   (perioMeasure.IntTooth)+", "
				+"ToothValue     =  "+POut.Int   (perioMeasure.ToothValue)+", "
				+"MBvalue        =  "+POut.Int   (perioMeasure.MBvalue)+", "
				+"Bvalue         =  "+POut.Int   (perioMeasure.Bvalue)+", "
				+"DBvalue        =  "+POut.Int   (perioMeasure.DBvalue)+", "
				+"MLvalue        =  "+POut.Int   (perioMeasure.MLvalue)+", "
				+"Lvalue         =  "+POut.Int   (perioMeasure.Lvalue)+", "
				+"DLvalue        =  "+POut.Int   (perioMeasure.DLvalue)+" "
				+"WHERE PerioMeasureNum = "+POut.Long(perioMeasure.PerioMeasureNum);
			Db.NonQ(command);
		}

		///<summary>Updates one PerioMeasure in the database.  Uses an old object to compare to, and only alters changed fields.  This prevents collisions and concurrency problems in heavily used tables.</summary>
		internal static void Update(PerioMeasure perioMeasure,PerioMeasure oldPerioMeasure){
			string command="";
			if(perioMeasure.PerioExamNum != oldPerioMeasure.PerioExamNum) {
				if(command!=""){ command+=",";}
				command+="PerioExamNum = "+POut.Long(perioMeasure.PerioExamNum)+"";
			}
			if(perioMeasure.SequenceType != oldPerioMeasure.SequenceType) {
				if(command!=""){ command+=",";}
				command+="SequenceType = "+POut.Int   ((int)perioMeasure.SequenceType)+"";
			}
			if(perioMeasure.IntTooth != oldPerioMeasure.IntTooth) {
				if(command!=""){ command+=",";}
				command+="IntTooth = "+POut.Int(perioMeasure.IntTooth)+"";
			}
			if(perioMeasure.ToothValue != oldPerioMeasure.ToothValue) {
				if(command!=""){ command+=",";}
				command+="ToothValue = "+POut.Int(perioMeasure.ToothValue)+"";
			}
			if(perioMeasure.MBvalue != oldPerioMeasure.MBvalue) {
				if(command!=""){ command+=",";}
				command+="MBvalue = "+POut.Int(perioMeasure.MBvalue)+"";
			}
			if(perioMeasure.Bvalue != oldPerioMeasure.Bvalue) {
				if(command!=""){ command+=",";}
				command+="Bvalue = "+POut.Int(perioMeasure.Bvalue)+"";
			}
			if(perioMeasure.DBvalue != oldPerioMeasure.DBvalue) {
				if(command!=""){ command+=",";}
				command+="DBvalue = "+POut.Int(perioMeasure.DBvalue)+"";
			}
			if(perioMeasure.MLvalue != oldPerioMeasure.MLvalue) {
				if(command!=""){ command+=",";}
				command+="MLvalue = "+POut.Int(perioMeasure.MLvalue)+"";
			}
			if(perioMeasure.Lvalue != oldPerioMeasure.Lvalue) {
				if(command!=""){ command+=",";}
				command+="Lvalue = "+POut.Int(perioMeasure.Lvalue)+"";
			}
			if(perioMeasure.DLvalue != oldPerioMeasure.DLvalue) {
				if(command!=""){ command+=",";}
				command+="DLvalue = "+POut.Int(perioMeasure.DLvalue)+"";
			}
			if(command==""){
				return;
			}
			command="UPDATE periomeasure SET "+command
				+" WHERE PerioMeasureNum = "+POut.Long(perioMeasure.PerioMeasureNum);
			Db.NonQ(command);
		}

		///<summary>Deletes one PerioMeasure from the database.</summary>
		internal static void Delete(long perioMeasureNum){
			string command="DELETE FROM periomeasure "
				+"WHERE PerioMeasureNum = "+POut.Long(perioMeasureNum);
			Db.NonQ(command);
		}

	}
}