#!/bin/bash

# Script to package Open Dental on the build server.
# Will probably fail on other computers
#
# References:
# * http://www.debian.org/doc/maint-guide/ch-first.en.html

opendentalversion=5.1
packageversion=0opendental1
version=${opendentalversion}-${packageversion}
currentdir=`pwd`
echo Packaging Open Dental version $opendentalversion for Debian as version $version

# Check for required directories
mkdir -p ~/source
mkdir -p ~/build
mkdir -p ~/packages
mkdir -p ~/downloads

# Check out or update the sources
cd ~/source

# Check out sources if required, else update
if [ ! -d "opendental5.1" ]; then
    svn co https://70.90.133.65:23793/svn/opendental/head/ opendental5.1/
else
    svn update opendental5.1/
fi

# Remove and re-create the entire opendental directory
cd ~/build
rm -rf opendental
mkdir opendental
cd opendental

# Check out the sources and create a tarball
svn export ~/source/opendental5.1 opendental-${opendentalversion}/
tar -cvzf opendental-${opendentalversion}.tar.gz opendental-${opendentalversion}
rm -rf opendental-${opendentalversion}

# Copy the source tarball to the downloads directory, for public download
cp opendental-${opendentalversion}.tar.gz ~/downloads/

# We now have a source tarball. That's where the debian process starts. We'll unpack this tarball again, which may
# seem rather stupid -- but the goal is to follow the debian process from here.
tar -xvzf opendental-${opendentalversion}.tar.gz
cd opendental-${opendentalversion}
# Copy the packaging/debian folder to the main folder
cp -r packaging/opendental/debian/ .
# For now, pass the -d parameter. This means that missing build 
# dependencies are no problem. Required when using Mono SVN.
dpkg-buildpackage -rfakeroot

# Copy output files to ~/packages
cd ../build-area
cp *.diff.gz ~/packages/
cp *.dsc ~/packages/
cp *.changes ~/packages/
cp *.deb ~/packages/
cp *.tar.gz ~/packages/

cd ${currentdir}
