//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenDental.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenDental.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap butCopy {
            get {
                object obj = ResourceManager.GetObject("butCopy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap butExport {
            get {
                object obj = ResourceManager.GetObject("butExport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap butExportExcel {
            get {
                object obj = ResourceManager.GetObject("butExportExcel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap butGoTo {
            get {
                object obj = ResourceManager.GetObject("butGoTo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap butLabel {
            get {
                object obj = ResourceManager.GetObject("butLabel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap butPaste {
            get {
                object obj = ResourceManager.GetObject("butPaste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap butPin {
            get {
                object obj = ResourceManager.GetObject("butPin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap butPreview {
            get {
                object obj = ResourceManager.GetObject("butPreview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap butPrint {
            get {
                object obj = ResourceManager.GetObject("butPrint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap butPrintSmall {
            get {
                object obj = ResourceManager.GetObject("butPrintSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap butQView {
            get {
                object obj = ResourceManager.GetObject("butQView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap butRecall {
            get {
                object obj = ResourceManager.GetObject("butRecall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap butZoomIn {
            get {
                object obj = ResourceManager.GetObject("butZoomIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap butZoomOut {
            get {
                object obj = ResourceManager.GetObject("butZoomOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] canadiancarriers {
            get {
                object obj = ResourceManager.GetObject("canadiancarriers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CDAErrorMessagesEn {
            get {
                object obj = ResourceManager.GetObject("CDAErrorMessagesEn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CDAErrorMessagesFr {
            get {
                object obj = ResourceManager.GetObject("CDAErrorMessagesFr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\froman\fcharset0 Times New Roman;}{\f1\fswiss\fcharset0 Arial;}}
        ///{\colortbl ;\red0\green0\blue0;}
        ///{\*\generator Msftedit 5.41.15.1507;}\viewkind4\uc1\pard\cf1\b\f0\fs24 CDT Content End User License\par
        ///\par
        ///Definitions\par
        ///\par
        ///\pard\sa240\b0\ldblquote CDT\rdblquote  means the textual, graphic and other editorial content included in the ADA developed publications titled \ul\i CDT-2007/2008: Current Dental Terminology \ulnone\i0 (\ldblquote CDT-200 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CDT_Content_End_User_License {
            get {
                return ResourceManager.GetString("CDT_Content_End_User_License", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Check_mark_23x20_02 {
            get {
                object obj = ResourceManager.GetObject("Check_mark_23x20_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ClaimForm xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Description&gt;ADA 2006&lt;/Description&gt;
        ///  &lt;FontName&gt;Arial&lt;/FontName&gt;
        ///  &lt;FontSize&gt;9&lt;/FontSize&gt;
        ///  &lt;UniqueID&gt;OD8&lt;/UniqueID&gt;
        ///  &lt;PrintImages&gt;true&lt;/PrintImages&gt;
        ///  &lt;Items&gt;
        ///    &lt;ClaimFormItem&gt;
        ///      &lt;ImageFileName&gt;ADA2006.gif&lt;/ImageFileName&gt;
        ///      &lt;FieldName /&gt;
        ///      &lt;FormatString /&gt;
        ///      &lt;XPos&gt;-1&lt;/XPos&gt;
        ///      &lt;YPos&gt;12&lt;/YPos&gt;
        ///      &lt;Width&gt;853&lt;/Width&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClaimForm2006 {
            get {
                return ResourceManager.GetString("ClaimForm2006", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap commlog {
            get {
                object obj = ResourceManager.GetObject("commlog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap deleteX {
            get {
                object obj = ResourceManager.GetObject("deleteX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap editPencil {
            get {
                object obj = ResourceManager.GetObject("editPencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Left {
            get {
                object obj = ResourceManager.GetObject("Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfProcedureCode xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;ProcedureCode&gt;
        ///    &lt;ProcCode&gt;N4101&lt;/ProcCode&gt;
        ///    &lt;Descript&gt;Post Op&lt;/Descript&gt;
        ///    &lt;AbbrDesc&gt;PostOp&lt;/AbbrDesc&gt;
        ///    &lt;ProcTime&gt;/X/&lt;/ProcTime&gt;
        ///    &lt;TreatArea&gt;Mouth&lt;/TreatArea&gt;
        ///    &lt;SetRecall&gt;false&lt;/SetRecall&gt;
        ///    &lt;NoBillIns&gt;true&lt;/NoBillIns&gt;
        ///    &lt;IsProsth&gt;false&lt;/IsProsth&gt;
        ///    &lt;IsHygiene&gt;false&lt;/IsHygiene&gt;
        ///    &lt;PaintType&gt;None&lt;/PaintType&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoFeeProcCodes {
            get {
                return ResourceManager.GetString("NoFeeProcCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Report Name=&quot;&quot;&gt;
        ///  &lt;Description&gt;
        ///  &lt;/Description&gt;
        ///  &lt;Author&gt;
        ///  &lt;/Author&gt;
        ///  &lt;PageHeight&gt;11in&lt;/PageHeight&gt;
        ///  &lt;PageWidth&gt;8.5in&lt;/PageWidth&gt;
        ///  &lt;Width&gt;7.5in&lt;/Width&gt;
        ///  &lt;TopMargin&gt;.25in&lt;/TopMargin&gt;
        ///  &lt;LeftMargin&gt;.25in&lt;/LeftMargin&gt;
        ///  &lt;RightMargin&gt;.25in&lt;/RightMargin&gt;
        ///  &lt;BottomMargin&gt;.25in&lt;/BottomMargin&gt;
        ///  &lt;DataSets&gt;
        ///    &lt;DataSet Name=&quot;Assets&quot;&gt;
        ///      &lt;Query&gt;
        ///        &lt;DataSourceName&gt;DS1&lt;/DataSourceName&gt;
        ///        &lt;Timeout&gt;10&lt;/Timeout&gt;
        ///        &lt;CommandText&gt;SELECT De [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReportAccountingBalanceSheet {
            get {
                return ResourceManager.GetString("ReportAccountingBalanceSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Report Name=&quot;&quot;&gt;
        ///  &lt;Description&gt;
        ///  &lt;/Description&gt;
        ///  &lt;Author&gt;
        ///  &lt;/Author&gt;
        ///  &lt;PageHeight&gt;11in&lt;/PageHeight&gt;
        ///  &lt;PageWidth&gt;8.5in&lt;/PageWidth&gt;
        ///  &lt;Width&gt;7.5in&lt;/Width&gt;
        ///  &lt;TopMargin&gt;.25in&lt;/TopMargin&gt;
        ///  &lt;LeftMargin&gt;.25in&lt;/LeftMargin&gt;
        ///  &lt;RightMargin&gt;.25in&lt;/RightMargin&gt;
        ///  &lt;BottomMargin&gt;.25in&lt;/BottomMargin&gt;
        ///  &lt;DataSets&gt;
        ///    &lt;DataSet Name=&quot;Data&quot;&gt;
        ///      &lt;Query&gt;
        ///        &lt;DataSourceName&gt;DS1&lt;/DataSourceName&gt;
        ///        &lt;Timeout&gt;10&lt;/Timeout&gt;
        ///        &lt;CommandText&gt;SELECT acco [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReportAccountingGenLedger {
            get {
                return ResourceManager.GetString("ReportAccountingGenLedger", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Right {
            get {
                object obj = ResourceManager.GetObject("Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stationary_sample1 {
            get {
                object obj = ResourceManager.GetObject("stationary sample1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Report Name=&quot;&quot;&gt;
        ///  &lt;CodeModules&gt;
        ///    &lt;CodeModule&gt;ODR.dll&lt;/CodeModule&gt;
        ///  &lt;/CodeModules&gt;
        ///  &lt;Classes&gt;
        ///    &lt;Class&gt;
        ///      &lt;ClassName&gt;ODR.Query&lt;/ClassName&gt;
        ///      &lt;InstanceName&gt;Query&lt;/InstanceName&gt;
        ///    &lt;/Class&gt;
        ///  &lt;/Classes&gt;
        ///  &lt;Description&gt;
        ///  &lt;/Description&gt;
        ///  &lt;Author&gt;
        ///  &lt;/Author&gt;
        ///  &lt;PageHeight&gt;11in&lt;/PageHeight&gt;
        ///  &lt;PageWidth&gt;8.5in&lt;/PageWidth&gt;
        ///  &lt;DataSources&gt;
        ///    &lt;DataSource Name=&quot;DS1&quot;&gt;
        ///      &lt;ConnectionProperties&gt;
        ///        &lt;DataProvider&gt;MySQL.NET&lt;/DataProvide [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Unsched_Treat_Plans {
            get {
                return ResourceManager.GetString("Unsched_Treat_Plans", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap up {
            get {
                object obj = ResourceManager.GetObject("up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
